/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.progavud.parcial1pa.vista;

/**
 *
 * @author jjuan
 */
public class ConsultarRazaView extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarRazaView
     */
    public ConsultarRazaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        separatorLinea = new javax.swing.JSeparator();
        lblConsultarRaza = new javax.swing.JLabel();
        separatorLinea1 = new javax.swing.JSeparator();
        lblNombreRaza = new javax.swing.JLabel();
        lblCodigoEMS = new javax.swing.JLabel();
        txtNombreRaza = new javax.swing.JTextField();
        txtCodigoEMS = new javax.swing.JTextField();
        buttonLimpiar = new javax.swing.JButton();
        buttonVolver = new javax.swing.JButton();
        buttonConsultar = new javax.swing.JButton();
        lblResultados = new javax.swing.JLabel();
        panelResultados = new javax.swing.JPanel();
        lblResultadoRaza = new javax.swing.JLabel();
        lblResultadoCodigo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtResultadoRaza = new javax.swing.JTextField();
        txtResultadoCodigo = new javax.swing.JTextField();
        txtResultadoDescripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ConsultarRazaView");

        panelFondo.setBackground(new java.awt.Color(255, 229, 180));

        separatorLinea.setBackground(new java.awt.Color(0, 0, 0));
        separatorLinea.setForeground(new java.awt.Color(0, 0, 0));

        lblConsultarRaza.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        lblConsultarRaza.setText("Consultar Raza De Gato");

        separatorLinea1.setBackground(new java.awt.Color(0, 0, 0));
        separatorLinea1.setForeground(new java.awt.Color(0, 0, 0));

        lblNombreRaza.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblNombreRaza.setText("Nombre de la raza:");
        lblNombreRaza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblCodigoEMS.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblCodigoEMS.setText("Codigo EMS");
        lblCodigoEMS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        txtNombreRaza.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        txtCodigoEMS.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        buttonLimpiar.setBackground(new java.awt.Color(255, 255, 204));
        buttonLimpiar.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        buttonLimpiar.setForeground(new java.awt.Color(204, 204, 0));
        buttonLimpiar.setText("Limpiar");
        buttonLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 2));
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });

        buttonVolver.setBackground(new java.awt.Color(255, 204, 204));
        buttonVolver.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        buttonVolver.setForeground(new java.awt.Color(204, 0, 0));
        buttonVolver.setText("Volver");
        buttonVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        buttonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVolverActionPerformed(evt);
            }
        });

        buttonConsultar.setBackground(new java.awt.Color(204, 255, 229));
        buttonConsultar.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        buttonConsultar.setForeground(new java.awt.Color(0, 153, 102));
        buttonConsultar.setText("Consultar");
        buttonConsultar.setToolTipText("");
        buttonConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        buttonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultarActionPerformed(evt);
            }
        });

        lblResultados.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblResultados.setText("Resultados:");
        lblResultados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        panelResultados.setBackground(new java.awt.Color(255, 250, 230));
        panelResultados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 120, 40), 2));

        lblResultadoRaza.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblResultadoRaza.setText("Raza:");

        lblResultadoCodigo.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblResultadoCodigo.setText("Codigo EMS:");

        lblDescripcion.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblDescripcion.setText("Descripcion:");

        txtResultadoRaza.setEditable(false);
        txtResultadoRaza.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        txtResultadoCodigo.setEditable(false);
        txtResultadoCodigo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        txtResultadoDescripcion.setEditable(false);
        txtResultadoDescripcion.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResultadosLayout.createSequentialGroup()
                        .addComponent(lblResultadoRaza)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblResultadoCodigo)
                        .addComponent(lblDescripcion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultadoRaza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtResultadoCodigo)
                        .addComponent(txtResultadoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultadoRaza)
                    .addComponent(txtResultadoRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultadoCodigo)
                    .addComponent(txtResultadoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtResultadoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separatorLinea)
            .addComponent(separatorLinea1)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblConsultarRaza))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoEMS)
                            .addComponent(lblNombreRaza))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreRaza, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txtCodigoEMS))))
                .addGap(28, 28, 28))
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblResultados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFondoLayout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(buttonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(buttonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(buttonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblConsultarRaza)
                .addGap(18, 18, 18)
                .addComponent(separatorLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRaza)
                    .addComponent(txtNombreRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoEMS)
                    .addComponent(txtCodigoEMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addComponent(separatorLinea1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultados)
                .addGap(12, 12, 12)
                .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFondoLayout.createSequentialGroup()
                    .addGap(229, 229, 229)
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(229, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVolverActionPerformed

    private void buttonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarRazaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarRazaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarRazaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarRazaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarRazaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConsultar;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JLabel lblCodigoEMS;
    private javax.swing.JLabel lblConsultarRaza;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombreRaza;
    private javax.swing.JLabel lblResultadoCodigo;
    private javax.swing.JLabel lblResultadoRaza;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JSeparator separatorLinea;
    private javax.swing.JSeparator separatorLinea1;
    private javax.swing.JTextField txtCodigoEMS;
    private javax.swing.JTextField txtNombreRaza;
    private javax.swing.JTextField txtResultadoCodigo;
    private javax.swing.JTextField txtResultadoDescripcion;
    private javax.swing.JTextField txtResultadoRaza;
    // End of variables declaration//GEN-END:variables
}
