/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.progavud.parcial1pa.vista;

/**
 *
 * @author jjuan
 */
public class InsertarRazaView extends javax.swing.JFrame {

    /**
     * Creates new form InsertarRazaView
     */
    public InsertarRazaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        separatorLinea = new javax.swing.JSeparator();
        lblInsertarNuevaRaza = new javax.swing.JLabel();
        lblNombreRaza = new javax.swing.JLabel();
        lblCodigoRaza = new javax.swing.JLabel();
        lblPatron = new javax.swing.JLabel();
        lblColorOjos = new javax.swing.JLabel();
        lblTipoCola = new javax.swing.JLabel();
        lblTipoOrejas = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        separatorLineaAbajo = new javax.swing.JSeparator();
        buttonLimpiar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        buttonGuardar = new javax.swing.JButton();
        txtCodigoRaza = new javax.swing.JTextField();
        txtNombreRaza1 = new javax.swing.JTextField();
        comboColor = new javax.swing.JComboBox<>();
        comboPatron = new javax.swing.JComboBox<>();
        comboColorOjos = new javax.swing.JComboBox<>();
        comboTipoCola = new javax.swing.JComboBox<>();
        comboTipoOrejas = new javax.swing.JComboBox<>();
        txtDescripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insertar Nueva Raza");
        setPreferredSize(new java.awt.Dimension(342, 371));

        panelFondo.setBackground(new java.awt.Color(255, 229, 180));

        separatorLinea.setBackground(new java.awt.Color(0, 0, 0));
        separatorLinea.setForeground(new java.awt.Color(0, 0, 0));

        lblInsertarNuevaRaza.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        lblInsertarNuevaRaza.setText("Insetar Nueva Raza");

        lblNombreRaza.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblNombreRaza.setText("Nombre de la raza:");
        lblNombreRaza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblCodigoRaza.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblCodigoRaza.setText("Codigo de la raza:");
        lblCodigoRaza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblPatron.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblPatron.setText("Patron:");
        lblPatron.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblColorOjos.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblColorOjos.setText("Color de ojos:");
        lblColorOjos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblTipoCola.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblTipoCola.setText("Tipo de cola:");
        lblTipoCola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblTipoOrejas.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblTipoOrejas.setText("Tipo de orejas:");
        lblTipoOrejas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblDescripcion.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblDescripcion.setText("Descripcion:");
        lblDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblColor.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblColor.setText("Color:");
        lblColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        separatorLineaAbajo.setBackground(new java.awt.Color(0, 0, 0));
        separatorLineaAbajo.setForeground(new java.awt.Color(0, 0, 0));

        buttonLimpiar.setBackground(new java.awt.Color(255, 255, 204));
        buttonLimpiar.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        buttonLimpiar.setForeground(new java.awt.Color(204, 204, 0));
        buttonLimpiar.setText("Limpiar");
        buttonLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 2));
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });

        buttonCancelar.setBackground(new java.awt.Color(255, 204, 204));
        buttonCancelar.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        buttonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        buttonCancelar.setText("Cancelar");
        buttonCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonGuardar.setBackground(new java.awt.Color(204, 255, 229));
        buttonGuardar.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        buttonGuardar.setForeground(new java.awt.Color(0, 153, 102));
        buttonGuardar.setText("Guardar");
        buttonGuardar.setToolTipText("");
        buttonGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        txtCodigoRaza.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        txtCodigoRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoRazaActionPerformed(evt);
            }
        });

        txtNombreRaza1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        txtNombreRaza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRaza1ActionPerformed(evt);
            }
        });

        comboColor.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "n - Negro", "a - Azul", "b - Chocolate", "w - Blanco", "d - Rojo", "e - Crema" }));
        comboColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColorActionPerformed(evt);
            }
        });

        comboPatron.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        comboPatron.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "01 - Van", "03 - Bicolor", "09 - Con Blanco (Indefinido)", "23 - Tabby Caballa", "24 - Tabby Moteado", "25 - Ticked Tabby", " " }));

        comboColorOjos.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        comboColorOjos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "61 - Azul", "62 - Naranja/Cobre", "63 - Odd-eyed/Heterocromia", "64 - Verde", "65 - Amarillo/Dorado", "66 - Avellana/Ambar Claro" }));

        comboTipoCola.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        comboTipoCola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "51 - Sin Cola", "52 - Enroscada", "53 - Corta", "54 - Larga", "55 - Quebrada", "56 - Emplumada" }));

        comboTipoOrejas.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        comboTipoOrejas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "71 - Rectas", "72 - Rizadas", "73 - Plegadas", "74 - Grandes", "75 - Pequeñas", "76 - En Punta" }));

        txtDescripcion.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separatorLinea)
            .addComponent(separatorLineaAbajo)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoRaza)
                            .addComponent(lblPatron)
                            .addComponent(lblColorOjos)
                            .addComponent(lblTipoCola)
                            .addComponent(lblTipoOrejas)
                            .addComponent(lblDescripcion)
                            .addComponent(lblColor)
                            .addComponent(lblNombreRaza))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboTipoOrejas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboTipoCola, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(comboColorOjos, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(txtNombreRaza1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoRaza, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboColor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboPatron, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(lblInsertarNuevaRaza))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(buttonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblInsertarNuevaRaza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separatorLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(lblNombreRaza)
                        .addGap(18, 18, 18)
                        .addComponent(lblCodigoRaza)
                        .addGap(18, 18, 18)
                        .addComponent(lblColor)
                        .addGap(18, 18, 18)
                        .addComponent(lblPatron)
                        .addGap(18, 18, 18)
                        .addComponent(lblColorOjos)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipoCola)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipoOrejas)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescripcion))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(txtNombreRaza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(comboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboPatron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(comboColorOjos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboTipoCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboTipoOrejas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(separatorLineaAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void txtCodigoRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoRazaActionPerformed

    private void txtNombreRaza1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRaza1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreRaza1ActionPerformed

    private void comboColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarRazaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarRazaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarRazaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarRazaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarRazaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JComboBox<String> comboColorOjos;
    private javax.swing.JComboBox<String> comboPatron;
    private javax.swing.JComboBox<String> comboTipoCola;
    private javax.swing.JComboBox<String> comboTipoOrejas;
    private javax.swing.JLabel lblCodigoRaza;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColorOjos;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblInsertarNuevaRaza;
    private javax.swing.JLabel lblNombreRaza;
    private javax.swing.JLabel lblPatron;
    private javax.swing.JLabel lblTipoCola;
    private javax.swing.JLabel lblTipoOrejas;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JSeparator separatorLinea;
    private javax.swing.JSeparator separatorLineaAbajo;
    private javax.swing.JTextField txtCodigoRaza;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombreRaza1;
    // End of variables declaration//GEN-END:variables
}
