/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.progavud.parcial1pa.vista;

/**
 *
 * @author jjuan
 */
public class RevisarGatosView extends javax.swing.JFrame {

    /**
     * Creates new form RevisarGatosView
     */
    public RevisarGatosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        separatorLinea = new javax.swing.JSeparator();
        lblRevisarGatos = new javax.swing.JLabel();
        separatorLinea3 = new javax.swing.JSeparator();
        buttonActualizar = new javax.swing.JButton();
        buttonVolver = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblNombreRaza = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblPatron = new javax.swing.JLabel();
        lblColorOjos = new javax.swing.JLabel();
        lblTipoCola = new javax.swing.JLabel();
        lblCantidadBlanco = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        comboNombreRaza = new javax.swing.JComboBox<>();
        comboColor = new javax.swing.JComboBox<>();
        comboPatron = new javax.swing.JComboBox<>();
        comboColorOjos = new javax.swing.JComboBox<>();
        comboTipoCola = new javax.swing.JComboBox<>();
        comboCantidadBlanco = new javax.swing.JComboBox<>();
        txtOtro = new javax.swing.JTextField();
        buttonOtro = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        lblRevisar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 229, 180));

        separatorLinea.setBackground(new java.awt.Color(0, 0, 0));
        separatorLinea.setForeground(new java.awt.Color(0, 0, 0));

        lblRevisarGatos.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblRevisarGatos.setText("Revisar Gatos Con Informacion Incompleta");

        separatorLinea3.setBackground(new java.awt.Color(0, 0, 0));
        separatorLinea3.setForeground(new java.awt.Color(0, 0, 0));

        buttonActualizar.setBackground(new java.awt.Color(204, 255, 229));
        buttonActualizar.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        buttonActualizar.setForeground(new java.awt.Color(0, 153, 102));
        buttonActualizar.setText("Actualizar");
        buttonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));

        buttonVolver.setBackground(new java.awt.Color(255, 204, 204));
        buttonVolver.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        buttonVolver.setForeground(new java.awt.Color(204, 0, 0));
        buttonVolver.setText("Volver");
        buttonVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        buttonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVolverActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");
        lblNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblNombreRaza.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblNombreRaza.setText("Nombre de la raza:");
        lblNombreRaza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblColor.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblColor.setText("Color:");
        lblColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblPatron.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblPatron.setText("Patrón:");
        lblPatron.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblColorOjos.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblColorOjos.setText("Color de ojos:");
        lblColorOjos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblTipoCola.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblTipoCola.setText("Tipo de cola:");
        lblTipoCola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblCantidadBlanco.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblCantidadBlanco.setText("Cantidad de blanco en pelaje:");
        lblCantidadBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        lblDescripcion.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblDescripcion.setText("Descripción:");
        lblDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 64, 64), 2));

        txtNombre.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        comboNombreRaza.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N
        comboNombreRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", " " }));

        comboColor.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N
        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "n - Negro", "a - Azul", "b - Chocolate", "w - Blanco", "d - Rojo", "e - Crema" }));
        comboColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColorActionPerformed(evt);
            }
        });

        comboPatron.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N
        comboPatron.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "01 - Van", "03 - Bicolor", "09 - Con Blanco (Indefinido)", "23 - Tabby Caballa", "24 - Tabby Moteado", "25 - Ticked Tabby", " " }));

        comboColorOjos.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N
        comboColorOjos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "61 - Azul", "62 - Naranja/Cobre", "63 - Odd-eyed/Heterocromia", "64 - Verde", "65 - Amarillo/Dorado", "66 - Avellana/Ambar Claro" }));

        comboTipoCola.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N
        comboTipoCola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "51 - Sin Cola", "52 - Enroscada", "53 - Corta", "54 - Larga", "55 - Quebrada", "56 - Emplumada" }));

        comboCantidadBlanco.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N
        comboCantidadBlanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", " " }));

        txtOtro.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N

        buttonOtro.setBackground(new java.awt.Color(179, 217, 255));
        buttonOtro.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        buttonOtro.setForeground(new java.awt.Color(0, 51, 102));
        buttonOtro.setText("Otro");
        buttonOtro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 2));
        buttonOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOtroActionPerformed(evt);
            }
        });

        txtDescripcion.setFont(new java.awt.Font("Serif", 1, 17)); // NOI18N

        lblRevisar.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        lblRevisar.setText("Actualize los campos que falten");
        lblRevisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separatorLinea)
            .addComponent(separatorLinea3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(buttonActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonVolver)
                .addGap(110, 110, 110))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNombre)
                        .addComponent(lblPatron)
                        .addComponent(lblColorOjos)
                        .addComponent(lblTipoCola)
                        .addComponent(lblCantidadBlanco)
                        .addComponent(lblColor)
                        .addComponent(lblNombreRaza)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                        .addComponent(txtOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCantidadBlanco, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboTipoCola, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboColorOjos, javax.swing.GroupLayout.Alignment.TRAILING, 0, 481, Short.MAX_VALUE)
                            .addComponent(comboPatron, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboColor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboNombreRaza, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRevisarGatos)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRevisar)
                        .addGap(309, 309, 309))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblRevisarGatos)
                .addGap(18, 18, 18)
                .addComponent(separatorLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRevisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreRaza)
                        .addGap(18, 18, 18)
                        .addComponent(lblColor)
                        .addGap(18, 18, 18)
                        .addComponent(lblPatron)
                        .addGap(18, 18, 18)
                        .addComponent(lblColorOjos)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipoCola)
                        .addGap(18, 18, 18)
                        .addComponent(lblCantidadBlanco)
                        .addGap(65, 65, 65)
                        .addComponent(lblDescripcion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboNombreRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboPatron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboColorOjos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboTipoCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboCantidadBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonOtro)
                            .addComponent(txtOtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(separatorLinea3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonActualizar)
                    .addComponent(buttonVolver))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVolverActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void comboColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboColorActionPerformed

    private void buttonOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOtroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevisarGatosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevisarGatosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevisarGatosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevisarGatosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevisarGatosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonActualizar;
    private javax.swing.JButton buttonOtro;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JComboBox<String> comboCantidadBlanco;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JComboBox<String> comboColorOjos;
    private javax.swing.JComboBox<String> comboNombreRaza;
    private javax.swing.JComboBox<String> comboPatron;
    private javax.swing.JComboBox<String> comboTipoCola;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidadBlanco;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColorOjos;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreRaza;
    private javax.swing.JLabel lblPatron;
    private javax.swing.JLabel lblRevisar;
    private javax.swing.JLabel lblRevisarGatos;
    private javax.swing.JLabel lblTipoCola;
    private javax.swing.JSeparator separatorLinea;
    private javax.swing.JSeparator separatorLinea3;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOtro;
    // End of variables declaration//GEN-END:variables
}
